version: '3'

services:

  djangoapp:
    build: .
    volumes:
      - .:/project
      - static_volume:/project/Compendium/Compendium/static/  # <-- bind the static volume
      - media_volume:/project/Compendium/Compendium/media/  # <-- bind the media volume
    networks:  # <-- here
      - nginx_network
      - compendium_prod_network  # <-- connect to the bridge

    depends_on:  # <-- wait for db to be "ready" before starting the app
      - compendium_prod

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/project/Compendium/Compendium/static/  # <-- bind the static volume
      - media_volume:/project/Compendium/Compendium/media/  # <-- bind the media volume
    depends_on:  # <-- wait for djangoapp to be "ready" before starting this service
      - djangoapp

    networks:  # <-- here
      - nginx_network

  compendium_prod:  # <-- IMPORTANT: same name as in DATABASES setting, otherwise Django won't find the database!
    image: postgres:10
    ports:
      - 5432:5432
    env_file:  # <-- we use the previously defined values
      - config/db/compendium_prod_env
    networks:  # <-- connect to the bridge
      - compendium_prod_network
    volumes:
      - compendium_prod_volume:/var/lib/postgresql/data

networks:  # <-- and here
  nginx_network:
    driver: bridge

  compendium_prod_network:  # <-- add the bridge
    driver: bridge

volumes:
  compendium_prod_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
