# Generated by Django 2.1.3 on 2018-11-18 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compendium_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.TextField()),
                ('idea', models.TextField()),
                ('application', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='id',
            new_name='journal_id',
        ),
        migrations.AddField(
            model_name='idea',
            name='journal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compendium_app.Journal'),
        ),
        migrations.AddField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
