# Generated by Django 2.1.3 on 2018-11-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium_app', '0002_auto_20181118_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='application',
            field=models.CharField(max_length=200),
        ),
    ]
