# Generated by Django 2.1.3 on 2018-11-18 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compendium_app', '0003_auto_20181118_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aphorism',
            fields=[
                ('aphorism_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.TextField()),
                ('aphorism', models.TextField()),
                ('application', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('decision_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.TextField()),
                ('decision', models.TextField()),
                ('application', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('principle_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.TextField()),
                ('principle', models.TextField()),
                ('application', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='id',
            new_name='idea_id',
        ),
        migrations.AlterField(
            model_name='journal',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='principle',
            name='journal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compendium_app.Journal'),
        ),
        migrations.AddField(
            model_name='principle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decision',
            name='journal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compendium_app.Journal'),
        ),
        migrations.AddField(
            model_name='decision',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aphorism',
            name='journal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compendium_app.Journal'),
        ),
        migrations.AddField(
            model_name='aphorism',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
