# Generated by Django 2.1.3 on 2018-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium_app', '0004_auto_20181119_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubEntries',
            fields=[
                ('subentries_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=10)),
                ('open_tag', models.CharField(max_length=10)),
                ('close_tag', models.CharField(max_length=10)),
            ],
        ),
    ]
