# Generated by Django 2.1.3 on 2018-11-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compendium_app', '0005_subentries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubEntries',
            new_name='Subentry',
        ),
    ]
