# Generated by Django 2.1.3 on 2018-12-01 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compendium_app', '0007_journal_data_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='idea',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
