# Generated by Django 2.1.3 on 2018-12-01 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compendium_app', '0008_auto_20181201_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aphorism',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='principle',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='aphorism',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decision',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='principle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subentry',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subentry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
