# Generated by Django 2.1.3 on 2018-12-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compendium_app', '0009_auto_20181201_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aphorism',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='principle',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='subentry',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='principle',
            old_name='journal_id',
            new_name='journal',
        ),
    ]
