# Generated by Django 2.1.3 on 2018-12-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compendium_app', '0012_auto_20181202_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='journal_id',
            new_name='journal',
        ),
    ]
